# ***** GAME CONFIG *****

# >> ARMAS

# 1) Arma inicial
MUNICION_ARMA_INICIAL_INFINITA: 10000
VEL_DIS_INICIAL: 0
VEL_PROY_INICIAL: 0
DANO_INICIAL: 0

# 2) Arma 1
MUNICION_ARMA1: 10
VEL_DIS_ARMA1: 10
VEL_PROY_ARMA1: 10
DANO_ARMA1: 10

# 3) Arma 2
MUNICION_ARMA2: 20
VEL_DIS_ARMA2: 20
VEL_PROY_ARMA2: 20
DANO_ARMA2: 20


# >> COLECCIONABLES
PUNTOS_GEMAS: 100
PUNTOS_MONEDAS: 50


# >> ENEMIGOS
NUMERO_INICIAL_ENEMIGOS: 5

# 1) Enemigo 1
POS_x_INICIAL_ENEMIGO_1: 5
POS_y_INICIAL_ENEMIGO_1: 0
VIDAS_ENEMIGO_1: 1
DANIO_ENEMIGO_1: 1
PUNTOS_ENEMIGO_1: 1

# 2) Enemigo 2
POS_x_INICIAL_ENEMIGO_2: 15
POS_y_INICIAL_ENEMIGO_2: 0
VIDAS_ENEMIGO_2: 2
DANIO_ENEMIGO_2: 2
PUNTOS_ENEMIGO_2: 2

# 3) Enemigo 3
POS_x_INICIAL_ENEMIGO_3: 30
POS_y_INICIAL_ENEMIGO_3: 5
VIDAS_ENEMIGO_3: 3
DANIO_ENEMIGO_3: 3
PUNTOS_ENEMIGO_3: 3


# >> PERSONAJE
PUNTOS_INICIALES: 0
VIDA_INICIAL: 10


# >> POSICION
X_INICIAL: 0
Y_INICIAL: 0
