#ifndef _COMMON_PROTOCOL_UTILS_H_
#define _COMMON_PROTOCOL_UTILS_H_

#define DISPARAR 0x01
#define MOVER_DERECHA 0x02
#define MOVER_DERECHA_RAPIDO 0x03
#define MOVER_IZQUIERDA 0x04
#define MOVER_IZQUIERDA_RAPIDO 0x05
#define MOVER_ARRIBA 0x06
#define MOVER_ABAJO 0x07
#define SALTAR 0x08

#endif
