# ***** GAME CONFIG *****
MINUTOS_DE_PARTIDA: 5

# >> ARMAS

# 1) Arma inicial
MUNICION_ARMA_INICIAL_INFINITA: 10000
VEL_DIS_INICIAL: 5
VEL_PROY_INICIAL: 5
DANO_INICIAL: 5

# 2) Arma 1
MUNICION_ARMA1: 10
VEL_DIS_ARMA1: 10
VEL_PROY_ARMA1: 10
DANO_ARMA1: 10

# 3) Arma 2
MUNICION_ARMA2: 20
VEL_DIS_ARMA2: 20
VEL_PROY_ARMA2: 20
DANO_ARMA2: 20


# >> COLECCIONABLES
PUNTOS_GEMAS: 100
PUNTOS_MONEDAS: 50
VIDAS_ZANAHORIAS: 5


# >> ENEMIGOS
NUMERO_INICIAL_ENEMIGOS: 5

# 1) Enemigo 1
VIDAS_ENEMIGO_1: 1
DANIO_ENEMIGO_1: 1
PUNTOS_ENEMIGO_1: 1
PROBA_DROPPEAR_MUNICION_ENEMIGO_1: 0.1
PROBA_DROPPEAR_VIDA_ENEMIGO_1: 0.1
SEGUNDOS_PARA_REVIVIR_ENEMIGO_1: 10

# 2) Enemigo 2
VIDAS_ENEMIGO_2: 2
DANIO_ENEMIGO_2: 2
PUNTOS_ENEMIGO_2: 2
PROBA_DROPPEAR_MUNICION_ENEMIGO_2: 0.2
PROBA_DROPPEAR_VIDA_ENEMIGO_2: 0.2
SEGUNDOS_PARA_REVIVIR_ENEMIGO_2: 20

# 3) Enemigo 3
VIDAS_ENEMIGO_3: 3
DANIO_ENEMIGO_3: 3
PUNTOS_ENEMIGO_3: 3
PROBA_DROPPEAR_MUNICION_ENEMIGO_3: 0.3
PROBA_DROPPEAR_VIDA_ENEMIGO_3: 0.3
SEGUNDOS_PARA_REVIVIR_ENEMIGO_3: 30


# >> PERSONAJE
PUNTOS_INICIALES: 0
VIDA_INICIAL: 10
X_INICIAL: 7
Y_INICIAL: 5
SEGUNDOS_PARA_REVIVIR_PERSONAJE: 5