#ifndef _COMMON_PROTOCOL_UTILS_H_
#define _COMMON_PROTOCOL_UTILS_H_

#define CREAR_PARTIDA 0x01
#define UNIRSE_A_PARTIDA 0x02

#define JAZZ 0x01
#define SPAZZ 0x02
#define LORI 0x03

#define DISPARAR 0x01
#define MOVER_DERECHA 0x02
#define MOVER_DERECHA_RAPIDO 0x03
#define MOVER_IZQUIERDA 0x04
#define MOVER_IZQUIERDA_RAPIDO 0x05
#define MOVER_ARRIBA 0x06
#define MOVER_ABAJO 0x07
#define SALTAR 0x08

#define ARMA_INICIAL 0x01
#define ARMA_SECUNDARIA 0x02


#endif
